name: "SIAN Tests for Julia"
on:
  pull_request:
  push:
    branches:
      - main
      - develop
    paths-ignore:
    - 'README.md'
    - 'Dockerfile'
    - '.gitignore'
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ["1.5.3"]
        julia-arch: [x64, x86]
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }} 
      - name: "Build Package"
        uses: julia-actions/julia-buildpkg@v1
      - name: "Check Load Path"
        run: julia -E "LOAD_PATH"
      - name: "Check Load Path from Base"
        run: julia -E "Base.load_path()"
      - name: "Run tests"
        uses: julia-actions/julia-runtest@v1

